vllm using port  50062
[W804 09:59:03.066898904 OperatorEntry.cpp:154] Warning: Warning only once for all operators,  other operators may also be overridden.
  Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::geometric_(Tensor(a!) self, float p, *, Generator? generator=None) -> Tensor(a!)
    registered at /pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: XPU
  previous kernel: registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:37
       new kernel: registered at /build/intel-pytorch-extension/build/Release/csrc/gpu/csrc/gpu/xpu/ATen/RegisterXPU_0.cpp:186 (function operator())
INFO 08-04 09:59:13 [__init__.py:248] Automatically detected platform xpu.
WARNING 08-04 09:59:15 [_logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 08-04 09:59:33 [config.py:752] This model supports multiple tasks: {'embed', 'classify', 'generate', 'score', 'reward'}. Defaulting to 'generate'.
WARNING 08-04 09:59:33 [_logger.py:68] device type=xpu is not supported by the V1 Engine. Falling back to V0. 
INFO 08-04 09:59:33 [config.py:1815] Defaulting to use mp for distributed inference
INFO 08-04 09:59:33 [config.py:1849] Disabled the custom all-reduce kernel because it is not supported on current platform.
ERROR 08-04 09:59:33 [xpu.py:104] Both start methods (spawn and fork) have issue on XPU if you use mp backend, setting it to ray instead.
INFO 08-04 09:59:33 [llm_engine.py:240] Initializing a V0 LLM engine (v0.8.5.dev562+gc44c384b1) with config: model='/scratch/group/hprc/llama-models/llama-3_3-70B', speculative_config=None, tokenizer='/scratch/group/hprc/llama-models/llama-3_3-70B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=xpu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=None, served_model_name=/scratch/group/hprc/llama-models/llama-3_3-70B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
WARNING 08-04 09:59:34 [_logger.py:68] No existing RAY instance detected. A new instance will be launched with current node resources.
2025-08-04 09:59:36,714	INFO worker.py:1888 -- Started a local Ray instance.
INFO 08-04 09:59:40 [ray_utils.py:335] No current placement group found. Creating a new placement group.
INFO 08-04 09:59:43 [ray_distributed_executor.py:176] use_ray_spmd_worker: False
[36m(pid=204872)[0m [W804 09:59:48.155661143 OperatorEntry.cpp:154] Warning: Warning only once for all operators,  other operators may also be overridden.
[36m(pid=204872)[0m   Overriding a previously registered kernel for the same operator and the same dispatch key
[36m(pid=204872)[0m   operator: aten::geometric_(Tensor(a!) self, float p, *, Generator? generator=None) -> Tensor(a!)
[36m(pid=204872)[0m     registered at /pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
[36m(pid=204872)[0m   dispatch key: XPU
[36m(pid=204872)[0m   previous kernel: registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:37
[36m(pid=204872)[0m        new kernel: registered at /build/intel-pytorch-extension/build/Release/csrc/gpu/csrc/gpu/xpu/ATen/RegisterXPU_0.cpp:186 (function operator())
[36m(pid=204872)[0m INFO 08-04 09:59:50 [__init__.py:248] Automatically detected platform xpu.
[36m(pid=204872)[0m WARNING 08-04 09:59:51 [_logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 08-04 09:59:52 [ray_distributed_executor.py:352] non_carry_over_env_vars from config: set()
INFO 08-04 09:59:52 [ray_distributed_executor.py:354] Copying the following environment variables to workers: ['VLLM_PORT', 'LD_LIBRARY_PATH', 'VLLM_USE_V1']
INFO 08-04 09:59:52 [ray_distributed_executor.py:357] If certain env vars should NOT be copied to workers, add them to /home/u.ks124812/.config/vllm/ray_non_carry_over_env_vars.json file
INFO 08-04 09:59:53 [xpu.py:35] Cannot use None backend on XPU.
INFO 08-04 09:59:53 [xpu.py:36] Using IPEX attention backend.
[36m(RayWorkerWrapper pid=204869)[0m INFO 08-04 09:59:53 [xpu.py:35] Cannot use None backend on XPU.
[36m(RayWorkerWrapper pid=204869)[0m INFO 08-04 09:59:53 [xpu.py:36] Using IPEX attention backend.
INFO 08-04 09:59:54 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[1, 2, 3], buffer_handle=(3, 4194304, 6, 'psm_bd89e493'), local_subscribe_addr='ipc:///tmp/job.1209071/0568fd39-0b73-4e06-9ec2-ef6c96936324', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 08-04 09:59:54 [parallel_state.py:1004] rank 0 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 0
2025:08:04-09:59:54:(203868) |CCL_WARN| value of CCL_ATL_TRANSPORT changed to be ofi (default:mpi)
2025:08:04-09:59:54:(203868) |CCL_WARN| value of CCL_LOCAL_RANK changed to be 0 (default:-1)
2025:08:04-09:59:54:(203868) |CCL_WARN| value of CCL_LOCAL_SIZE changed to be 4 (default:-1)
2025:08:04-09:59:54:(203868) |CCL_WARN| value of CCL_PROCESS_LAUNCHER changed to be none (default:hydra)
2025:08:04-09:59:55:(203868) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode
[36m(RayWorkerWrapper pid=204869)[0m INFO 08-04 09:59:54 [parallel_state.py:1004] rank 1 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 1
[36m(RayWorkerWrapper pid=204869)[0m 2025:08:04-09:59:55:(204869) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode
[36m(pid=204873)[0m INFO 08-04 09:59:50 [__init__.py:248] Automatically detected platform xpu.[32m [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)[0m
Loading safetensors checkpoint shards:   0% Completed | 0/30 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   3% Completed | 1/30 [00:02<01:10,  2.43s/it]
Loading safetensors checkpoint shards:   7% Completed | 2/30 [00:08<02:11,  4.68s/it]
Loading safetensors checkpoint shards:  10% Completed | 3/30 [00:17<03:01,  6.73s/it]
Loading safetensors checkpoint shards:  13% Completed | 4/30 [00:25<03:03,  7.07s/it]
Loading safetensors checkpoint shards:  17% Completed | 5/30 [00:34<03:17,  7.92s/it]
Loading safetensors checkpoint shards:  20% Completed | 6/30 [00:42<03:09,  7.88s/it]
Loading safetensors checkpoint shards:  23% Completed | 7/30 [00:50<02:58,  7.75s/it]
Loading safetensors checkpoint shards:  27% Completed | 8/30 [00:57<02:45,  7.51s/it]
Loading safetensors checkpoint shards:  30% Completed | 9/30 [01:04<02:39,  7.59s/it]
Loading safetensors checkpoint shards:  33% Completed | 10/30 [01:15<02:48,  8.44s/it]
Loading safetensors checkpoint shards:  37% Completed | 11/30 [01:27<03:02,  9.59s/it]
Loading safetensors checkpoint shards:  40% Completed | 12/30 [01:36<02:49,  9.39s/it]
Loading safetensors checkpoint shards:  43% Completed | 13/30 [01:45<02:40,  9.45s/it]
Loading safetensors checkpoint shards:  47% Completed | 14/30 [01:56<02:34,  9.67s/it]
Loading safetensors checkpoint shards:  50% Completed | 15/30 [02:06<02:27,  9.81s/it]
Loading safetensors checkpoint shards:  53% Completed | 16/30 [02:14<02:12,  9.47s/it]
Loading safetensors checkpoint shards:  57% Completed | 17/30 [02:25<02:07,  9.80s/it]
Loading safetensors checkpoint shards:  60% Completed | 18/30 [02:33<01:52,  9.34s/it]
Loading safetensors checkpoint shards:  63% Completed | 19/30 [02:40<01:32,  8.45s/it]
Loading safetensors checkpoint shards:  67% Completed | 20/30 [02:50<01:30,  9.10s/it]
Loading safetensors checkpoint shards:  70% Completed | 21/30 [03:00<01:22,  9.15s/it]
Loading safetensors checkpoint shards:  73% Completed | 22/30 [03:09<01:13,  9.24s/it]
Loading safetensors checkpoint shards:  77% Completed | 23/30 [03:19<01:06,  9.46s/it]
Loading safetensors checkpoint shards:  80% Completed | 24/30 [03:28<00:56,  9.44s/it]
Loading safetensors checkpoint shards:  83% Completed | 25/30 [03:31<00:37,  7.47s/it]
Loading safetensors checkpoint shards:  87% Completed | 26/30 [03:41<00:33,  8.30s/it]
Loading safetensors checkpoint shards:  90% Completed | 27/30 [03:50<00:25,  8.51s/it]
Loading safetensors checkpoint shards:  93% Completed | 28/30 [03:58<00:16,  8.30s/it]
Loading safetensors checkpoint shards:  97% Completed | 29/30 [04:07<00:08,  8.53s/it]
Loading safetensors checkpoint shards: 100% Completed | 30/30 [04:17<00:00,  8.73s/it]
Loading safetensors checkpoint shards: 100% Completed | 30/30 [04:17<00:00,  8.57s/it]

INFO 08-04 10:04:23 [default_loader.py:278] Loading weights took 257.17 seconds
WARNING 08-04 10:04:23 [_logger.py:68] Pin memory is not supported on XPU.
[36m(RayWorkerWrapper pid=204869)[0m INFO 08-04 10:04:23 [default_loader.py:278] Loading weights took 257.15 seconds
[36m(RayWorkerWrapper pid=204869)[0m WARNING 08-04 10:04:23 [_logger.py:68] Pin memory is not supported on XPU.
[36m(pid=204869)[0m WARNING 08-04 09:59:51 [_logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")[32m [repeated 3x across cluster][0m
[36m(RayWorkerWrapper pid=204873)[0m INFO 08-04 09:59:53 [xpu.py:35] Cannot use None backend on XPU.[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=204873)[0m INFO 08-04 09:59:53 [xpu.py:36] Using IPEX attention backend.[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=204873)[0m INFO 08-04 09:59:54 [parallel_state.py:1004] rank 3 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 3[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=204873)[0m 2025:08:04-09:59:55:(204873) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode[32m [repeated 2x across cluster][0m
INFO 08-04 10:04:24 [xpu_model_runner.py:414] Loading model weights took 32.8894 GiB
2025:08:04-10:04:26:(203868) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode
[36m(RayWorkerWrapper pid=204869)[0m INFO 08-04 10:04:24 [xpu_model_runner.py:414] Loading model weights took 32.8894 GiB
INFO 08-04 10:04:43 [executor_base.py:112] # xpu blocks: 8446, # CPU blocks: 3276
INFO 08-04 10:04:43 [executor_base.py:117] Maximum concurrency for 1024 tokens per request: 131.97x
INFO 08-04 10:04:44 [llm_engine.py:435] init engine (profile, create kv cache, warmup model) took 20.37 seconds
 * Serving Flask app 'app'
 * Debug mode: off
2025-08-04 10:04:44,644 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:1025
 * Running on http://127.0.0.1:1025
2025-08-04 10:04:44,644 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
