vllm using port  30634
[W520 11:02:41.792590837 OperatorEntry.cpp:154] Warning: Warning only once for all operators,  other operators may also be overridden.
  Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::geometric_(Tensor(a!) self, float p, *, Generator? generator=None) -> Tensor(a!)
    registered at /pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: XPU
  previous kernel: registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:37
       new kernel: registered at /build/intel-pytorch-extension/build/Release/csrc/gpu/csrc/gpu/xpu/ATen/RegisterXPU_0.cpp:186 (function operator())
INFO 05-20 11:02:55 [__init__.py:248] Automatically detected platform xpu.
WARNING 05-20 11:02:56 [_logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 05-20 11:03:13 [config.py:752] This model supports multiple tasks: {'generate', 'reward', 'classify', 'score', 'embed'}. Defaulting to 'generate'.
WARNING 05-20 11:03:13 [_logger.py:68] device type=xpu is not supported by the V1 Engine. Falling back to V0. 
INFO 05-20 11:03:13 [config.py:1815] Defaulting to use mp for distributed inference
INFO 05-20 11:03:13 [config.py:1849] Disabled the custom all-reduce kernel because it is not supported on current platform.
ERROR 05-20 11:03:13 [xpu.py:104] Both start methods (spawn and fork) have issue on XPU if you use mp backend, setting it to ray instead.
INFO 05-20 11:03:13 [llm_engine.py:240] Initializing a V0 LLM engine (v0.8.5.dev562+gc44c384b1) with config: model='/scratch/group/hprc/llama-models/llama-3_3-70B', speculative_config=None, tokenizer='/scratch/group/hprc/llama-models/llama-3_3-70B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=xpu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=None, served_model_name=/scratch/group/hprc/llama-models/llama-3_3-70B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
WARNING 05-20 11:03:13 [_logger.py:68] No existing RAY instance detected. A new instance will be launched with current node resources.
2025-05-20 11:03:17,405	INFO worker.py:1888 -- Started a local Ray instance.
INFO 05-20 11:03:21 [ray_utils.py:335] No current placement group found. Creating a new placement group.
INFO 05-20 11:03:26 [ray_distributed_executor.py:176] use_ray_spmd_worker: False
[36m(pid=1956675)[0m [W520 11:03:31.370103347 OperatorEntry.cpp:154] Warning: Warning only once for all operators,  other operators may also be overridden.
[36m(pid=1956675)[0m   Overriding a previously registered kernel for the same operator and the same dispatch key
[36m(pid=1956675)[0m   operator: aten::geometric_(Tensor(a!) self, float p, *, Generator? generator=None) -> Tensor(a!)
[36m(pid=1956675)[0m     registered at /pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
[36m(pid=1956675)[0m   dispatch key: XPU
[36m(pid=1956675)[0m   previous kernel: registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:37
[36m(pid=1956675)[0m        new kernel: registered at /build/intel-pytorch-extension/build/Release/csrc/gpu/csrc/gpu/xpu/ATen/RegisterXPU_0.cpp:186 (function operator())
[36m(pid=1956677)[0m INFO 05-20 11:03:32 [__init__.py:248] Automatically detected platform xpu.
[36m(pid=1956677)[0m WARNING 05-20 11:03:33 [_logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 05-20 11:03:34 [ray_distributed_executor.py:352] non_carry_over_env_vars from config: set()
INFO 05-20 11:03:34 [ray_distributed_executor.py:354] Copying the following environment variables to workers: ['VLLM_PORT', 'LD_LIBRARY_PATH', 'VLLM_USE_V1']
INFO 05-20 11:03:34 [ray_distributed_executor.py:357] If certain env vars should NOT be copied to workers, add them to /home/u.ks124812/.config/vllm/ray_non_carry_over_env_vars.json file
INFO 05-20 11:03:34 [xpu.py:35] Cannot use None backend on XPU.
INFO 05-20 11:03:34 [xpu.py:36] Using IPEX attention backend.
[36m(RayWorkerWrapper pid=1956676)[0m INFO 05-20 11:03:34 [xpu.py:35] Cannot use None backend on XPU.
[36m(RayWorkerWrapper pid=1956676)[0m INFO 05-20 11:03:34 [xpu.py:36] Using IPEX attention backend.
INFO 05-20 11:03:35 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[1, 2, 3], buffer_handle=(3, 4194304, 6, 'psm_62a42d34'), local_subscribe_addr='ipc:///tmp/job.1135476/4752c7e9-f85f-4207-b5cc-7418900a5e6e', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 05-20 11:03:36 [parallel_state.py:1004] rank 0 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 0
2025:05:20-11:03:36:(1954429) |CCL_WARN| value of CCL_ATL_TRANSPORT changed to be ofi (default:mpi)
2025:05:20-11:03:36:(1954429) |CCL_WARN| value of CCL_LOCAL_RANK changed to be 0 (default:-1)
2025:05:20-11:03:36:(1954429) |CCL_WARN| value of CCL_LOCAL_SIZE changed to be 4 (default:-1)
2025:05:20-11:03:36:(1954429) |CCL_WARN| value of CCL_PROCESS_LAUNCHER changed to be none (default:hydra)
2025:05:20-11:03:38:(1954429) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode
[36m(RayWorkerWrapper pid=1956676)[0m INFO 05-20 11:03:36 [parallel_state.py:1004] rank 1 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 1
[36m(RayWorkerWrapper pid=1956676)[0m 2025:05:20-11:03:38:(1956676) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode
[36m(pid=1956678)[0m INFO 05-20 11:03:32 [__init__.py:248] Automatically detected platform xpu.[32m [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)[0m
Loading safetensors checkpoint shards:   0% Completed | 0/30 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   3% Completed | 1/30 [00:03<01:47,  3.70s/it]
Loading safetensors checkpoint shards:   7% Completed | 2/30 [00:07<01:44,  3.74s/it]
Loading safetensors checkpoint shards:  10% Completed | 3/30 [00:10<01:38,  3.64s/it]
Loading safetensors checkpoint shards:  13% Completed | 4/30 [00:14<01:33,  3.59s/it]
Loading safetensors checkpoint shards:  17% Completed | 5/30 [00:16<01:18,  3.14s/it]
Loading safetensors checkpoint shards:  20% Completed | 6/30 [00:20<01:20,  3.33s/it]
Loading safetensors checkpoint shards:  23% Completed | 7/30 [00:23<01:11,  3.10s/it]
Loading safetensors checkpoint shards:  27% Completed | 8/30 [00:26<01:08,  3.10s/it]
Loading safetensors checkpoint shards:  30% Completed | 9/30 [00:30<01:09,  3.32s/it]
Loading safetensors checkpoint shards:  33% Completed | 10/30 [00:35<01:16,  3.83s/it]
Loading safetensors checkpoint shards:  37% Completed | 11/30 [00:40<01:22,  4.34s/it]
Loading safetensors checkpoint shards:  40% Completed | 12/30 [00:44<01:13,  4.07s/it]
Loading safetensors checkpoint shards:  43% Completed | 13/30 [00:47<01:07,  3.98s/it]
Loading safetensors checkpoint shards:  47% Completed | 14/30 [00:50<00:57,  3.57s/it]
Loading safetensors checkpoint shards:  50% Completed | 15/30 [00:53<00:53,  3.56s/it]
Loading safetensors checkpoint shards:  53% Completed | 16/30 [00:57<00:49,  3.51s/it]
Loading safetensors checkpoint shards:  57% Completed | 17/30 [01:00<00:43,  3.32s/it]
Loading safetensors checkpoint shards:  60% Completed | 18/30 [01:02<00:35,  2.92s/it]
Loading safetensors checkpoint shards:  63% Completed | 19/30 [01:04<00:30,  2.81s/it]
Loading safetensors checkpoint shards:  67% Completed | 20/30 [01:07<00:28,  2.83s/it]
Loading safetensors checkpoint shards:  70% Completed | 21/30 [01:11<00:27,  3.03s/it]
Loading safetensors checkpoint shards:  73% Completed | 22/30 [01:13<00:23,  2.96s/it]
Loading safetensors checkpoint shards:  77% Completed | 23/30 [01:17<00:21,  3.04s/it]
Loading safetensors checkpoint shards:  80% Completed | 24/30 [01:19<00:17,  2.94s/it]
Loading safetensors checkpoint shards:  83% Completed | 25/30 [01:21<00:13,  2.60s/it]
Loading safetensors checkpoint shards:  87% Completed | 26/30 [01:25<00:11,  2.86s/it]
Loading safetensors checkpoint shards:  90% Completed | 27/30 [01:27<00:07,  2.65s/it]
Loading safetensors checkpoint shards:  93% Completed | 28/30 [01:29<00:05,  2.62s/it]
Loading safetensors checkpoint shards:  97% Completed | 29/30 [01:32<00:02,  2.61s/it]
Loading safetensors checkpoint shards: 100% Completed | 30/30 [01:35<00:00,  2.80s/it]
Loading safetensors checkpoint shards: 100% Completed | 30/30 [01:35<00:00,  3.19s/it]

INFO 05-20 11:05:24 [default_loader.py:278] Loading weights took 95.73 seconds
WARNING 05-20 11:05:24 [_logger.py:68] Pin memory is not supported on XPU.
INFO 05-20 11:05:25 [xpu_model_runner.py:414] Loading model weights took 32.8894 GiB
2025:05:20-11:05:43:(1954429) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode
[36m(RayWorkerWrapper pid=1956677)[0m INFO 05-20 11:05:41 [default_loader.py:278] Loading weights took 112.05 seconds
[36m(RayWorkerWrapper pid=1956677)[0m WARNING 05-20 11:05:41 [_logger.py:68] Pin memory is not supported on XPU.
[36m(pid=1956678)[0m WARNING 05-20 11:03:33 [_logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")[32m [repeated 3x across cluster][0m
[36m(RayWorkerWrapper pid=1956678)[0m INFO 05-20 11:03:34 [xpu.py:35] Cannot use None backend on XPU.[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=1956678)[0m INFO 05-20 11:03:34 [xpu.py:36] Using IPEX attention backend.[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=1956678)[0m INFO 05-20 11:03:36 [parallel_state.py:1004] rank 3 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 3[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=1956678)[0m 2025:05:20-11:03:38:(1956678) |CCL_WARN| pidfd is not supported, fallbacks to drmfd exchange mode[32m [repeated 2x across cluster][0m
[36m(RayWorkerWrapper pid=1956676)[0m INFO 05-20 11:05:41 [xpu_model_runner.py:414] Loading model weights took 32.8894 GiB
INFO 05-20 11:06:00 [executor_base.py:112] # xpu blocks: 8446, # CPU blocks: 3276
INFO 05-20 11:06:00 [executor_base.py:117] Maximum concurrency for 1024 tokens per request: 131.97x
INFO 05-20 11:06:01 [llm_engine.py:435] init engine (profile, create kv cache, warmup model) took 20.15 seconds
 * Serving Flask app 'app'
 * Debug mode: off
2025-05-20 11:06:01,588 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:1025
 * Running on http://127.0.0.1:1025
2025-05-20 11:06:01,589 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
